# Generated by Django 5.1.2 on 2024-10-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_order', '0004_remove_cart_foods_remove_order_foods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=10),
        ),
    ]
