# Generated by Django 5.1.2 on 2024-10-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_order', '0006_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_cut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
