# Generated by Django 5.1.4 on 2024-12-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_order', '0007_order_promo_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
