# Generated by Django 5.1.2 on 2024-10-23 09:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0002_alter_restaurant_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('min_payment', models.FloatField()),
                ('promo_code', models.CharField(max_length=30)),
                ('expiry_date', models.DateField()),
                ('max_usage', models.IntegerField()),
                ('shown_to_public', models.BooleanField()),
                ('current_usage', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
