# Generated by Django 5.1.2 on 2024-10-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_remove_promo_current_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed Price', 'Fixed Price')], max_length=255),
        ),
    ]
