# Generated by Django 5.1.2 on 2024-10-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_alter_promo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='max_usage',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='promo',
            name='shown_to_public',
            field=models.BooleanField(default=False),
        ),
    ]
