# Generated by Django 5.1.2 on 2024-10-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_alter_promo_max_usage_alter_promo_shown_to_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
