# Generated by Django 5.1.2 on 2024-10-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-date_joined"]},
        ),
    ]
