# Generated by Django 5.1.2 on 2024-10-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_restaurant_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="price_range",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="categories",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
