# Generated by Django 5.1.2 on 2024-10-27 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_remove_restaurant_price_range_restaurant_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="placeholder_image",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(3),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
