# Generated by Django 5.1.2 on 2024-10-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_restaurant_placeholder_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="placeholder_image",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
